codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
  coverage:
    precision: 2
    round: down
    range: "70...100"

coverage:
  status:
    project:
      default:
        target: 90
        threshold: 2
    patch:
      default:
        target: 75
        threshold: 1
        base: auto
        only_pulls: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
