name: Actionlint

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    paths:
      - ".github/workflows/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run actionlint
        uses: raven-actions/actionlint@v2
